In [ ]:
# Import the needed libraries

**72. How to swap two rows of an array?** 

In [19]:
import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)
# swap
a[[0, 2]] = a[[2, 0]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


**75. How to compute averages using a sliding window over an array?**