In [ ]:
# Install torch and torchvision on your computer
# It's convenient to create a virtual env for that

In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
# set the torch manual seed to 42
seed = 42

In [9]:
# Create a tensor of shape (5,) and store in the features variable
features = 0
features = torch.tensor([1., -1., 0., 2., 1.])

In [10]:
# Generate a tensor called weights with the same shape of features
# Hint: search torch.rand_like
weights = torch.Tensor(5).random_(0, 10)

In [11]:
assert weights.shape == features.shape

In [12]:
weights

tensor([3., 1., 4., 1., 1.])

In [13]:
bias = torch.randn((1,1))

In [14]:
bias

tensor([[0.7895]])

In [15]:
# Implement the sigmoid function by using torch
from scipy.special import expit
def sigmoid(x):
    return expit(x)

In [32]:
# Use torch.dot function for multiplying weights and features and
# add the bias to the result. Store the result into the score variable

score = (torch.dot(features, weights) + bias)

score.shape

torch.Size([1, 1])

In [33]:
assert score.shape == (1,1)

In [34]:
# Use the defined sigmoid function to activate the score.
# Store the result in the prob variable

prob = sigmoid(score)


In [35]:
assert prob.shape == (1,1)

In [37]:
# Convert the a numpy array into a torch tensor
# Store it in the b variable
a = np.random.rand(4, 3)
a
b = a

In [38]:
assert b.shape == (4,3) 

In [42]:
# Do the opposite now. From the given tensor a convert it a numpy array
# Store the result in b
a = torch.tensor([1,2])
a
b = np.array(a)

In [43]:
assert type(b) == np.ndarray

In [47]:
# Reshape the given v tensor in a 10x10 tensor.
# Store the result in v_reshaped
# You can use various methods: reshape, view, resize... Check all of them

v = torch.randn((100,1)).reshape(10, 10)
v_reshaped = v


In [52]:
# create a tensor with shape (16, 32, 32, 3) containing only ones
# Store it in the ones variable
ones = torch.ones(16, 32, 32, 3)
ones

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         ...,

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1.

In [53]:
assert ones.shape == (16, 32, 32, 3)

In [58]:
import pandas as pd
import matplotlib.pyplot as plt
# load and plot the data using scatterplot with different colors for labels
data = pd.read_csv('data.csv', header=None)
data

0         1  2
0   0.78051 -0.063669  1
1   0.28774  0.291390  1
2   0.40714  0.178780  1
3   0.29230  0.421700  1
4   0.50922  0.352560  1
..      ...       ... ..
95  0.77029  0.701400  0
96  0.73156  0.717820  0
97  0.44556  0.579910  0
98  0.85275  0.859870  0
99  0.51912  0.623590  0

[100 rows x 3 columns]

In [60]:
plt.scatter(data[:,0:1],data[:,1:2],c=c)

TypeError: '(slice(None, None, None), slice(0, 1, None))' is an invalid key